allprojects {
  version = '0.10.0'
  group = 'com.joom.grip'

  ext.kotlinVersion = '2.4.0'
  ext.asmVersion = '9.2'
  ext.jsr305 = '3.0.2'
  ext.mavenPublishVersion = '0.36.0'

  ext.junitVersion = '4.13.2'
  ext.mockitoVersion = '4.0.0'

  buildscript {
    repositories {
      mavenLocal()
      mavenCentral()
    }

    dependencies {
      classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion"
      classpath "com.vanniktech:gradle-maven-publish-plugin:$mavenPublishVersion"
    }
  }

  repositories {
    mavenLocal()
    mavenCentral()
  }
}
